In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
Amazon_sale_df = pd.read_csv('/content/Amazon Sale Report.csv')

/tmp/ipython-input-615607781.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  Amazon_sale_df = pd.read_csv('/content/Amazon Sale Report.csv')

In [14]:
Amazon_sale_df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [15]:
Amazon_sale_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [16]:
Amazon_sale_df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

**HANDLING MISSING VALUES AND DROPPING IRRELEVANT COLUMNS**

In [17]:
Amazon_sale_df.drop(['Unnamed: 22'], axis=1, inplace=True)

In [18]:
Amazon_sale_df.drop(['fulfilled-by'], axis=1, inplace=True)

In [19]:
Amazon_sale_df['Courier Status'].fillna('Unknown', inplace=True)

/tmp/ipython-input-1742333857.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Amazon_sale_df['Courier Status'].fillna('Unknown', inplace=True)

In [20]:
Amazon_sale_df['promotion-ids'].fillna('No Promos', inplace=True)

/tmp/ipython-input-1613630806.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Amazon_sale_df['promotion-ids'].fillna('No Promos', inplace=True)

In [21]:
Amazon_sale_df['currency'].fillna(Amazon_sale_df['currency'].mode()[0], inplace=True)

/tmp/ipython-input-4192721645.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Amazon_sale_df['currency'].fillna(Amazon_sale_df['currency'].mode()[0], inplace=True)

In [22]:
Amazon_sale_df_backup = Amazon_sale_df.copy()

In [23]:
Amazon_sale_df[Amazon_sale_df['Amount'].isna()][['Status','Order ID','SKU','Qty','Amount']].head(50)

        Status             Order ID                    SKU  Qty  Amount
8    Cancelled  407-5443024-5233168    SET200-KR-NP-A-XXXL    0     NaN
29   Cancelled  404-5933402-8801952    JNE2132-KR-398-XXXL    0     NaN
65   Cancelled  171-4137548-0481151         JNE3373-KR-XXL    0     NaN
84   Cancelled  403-9950518-0349133           JNE3510-KR-M    0     NaN
95   Cancelled  405-9112089-3379536           JNE3405-KR-L    0     NaN
101  Cancelled  402-7841951-1872363         SET347-KR-NP-S    0     NaN
132  Cancelled  171-0293372-4913973      SET269-KR-NP-XXXL    0     NaN
139  Cancelled  403-6442534-2769112          J0300-TP-XXXL    0     NaN
155  Cancelled  402-8078642-8565124          JNE3887-KR-XL    0     NaN
165  Cancelled  406-0218328-1773963      PJNE2100-KR-N-6XL    0     NaN
205  Cancelled  403-4337144-0984323             J0340-TP-M    0     NaN
215  Cancelled  403-5456917-5571511          JNE3861-DR-XL    0     NaN
242  Cancelled  404-0634392-1837110             J0198-TP-S    0     NaN
249  Cancelled  404-8514200-3544346         JNE3440-KR-N-M    0     NaN
250  Cancelled  404-7452877-2137949           JNE3802-KR-M    0     NaN
271  Cancelled  404-1607808-0769930        SET265-KR-NP-XL    0     NaN
328  Cancelled  402-1365379-0131533            J0012-SKD-M    0     NaN
363  Cancelled  171-9620288-8918704         SET226-KR-PP-L    0     NaN
381  Cancelled  404-4026534-0431517      SET217-KR-PP-XXXL    0     NaN
413  Cancelled  171-5542306-9306709            J0308-DR-XL    0     NaN
428  Cancelled  171-4549643-0067500    JNE2270-KR-487-A-XL    0     NaN
448  Cancelled  407-3630361-4581152          JNE3619-KR-XS    0     NaN
456  Cancelled  407-5524319-6977912         JNE3727-KR-XXL    0     NaN
470  Cancelled  407-6861831-9368312        SET374-KR-NP-XS    0     NaN
489  Cancelled  408-8960391-6097167        JNE3781-KR-XXXL    0     NaN
500  Cancelled  405-4491602-9761902           J0308-DR-XXL    0     NaN
503  Cancelled  408-4378624-3886712           JNE3799-KR-S    0     NaN
509  Cancelled  408-7342331-1733136  JNE1525-KR-UDF19-A-XL    0     NaN
518  Cancelled  407-6910434-1793162           MEN5023-KR-S    0     NaN
521  Cancelled  404-0553710-6997951         MEN5002-KR-XXL    0     NaN
535  Cancelled  407-1181422-6183500         SET319-KR-NP-S    0     NaN
540  Cancelled  404-3977029-4836363         SET233-KR-PP-L    0     NaN
547  Cancelled  402-4976284-7401969     SET131-KR-NP-A-XXL    0     NaN
563  Cancelled  405-7730926-6032325          J0386-KR-XXXL    0     NaN
572  Cancelled  403-3416641-9569165          J0003-SET-XXL    0     NaN
593  Cancelled  171-7822891-4076363           J0008-SKD-XL    0     NaN
602  Cancelled  405-6917473-7822701      SET374-KR-NP-XXXL    0     NaN
630  Cancelled  405-1437048-4974713        SET324-KR-NP-XS    0     NaN
631  Cancelled  402-9348518-5984354        JNE3611-KR-XXXL    0     NaN
632  Cancelled  402-9348518-5984354         JNE3461-KR-XXL    0     NaN
633  Cancelled  406-8892825-4377127         SET388-KR-NP-L    0     NaN
639  Cancelled  408-8068196-8707526         JNE3437-KR-XXL    0     NaN
652  Cancelled  408-0987613-5525924            J0230-SKD-M    0     NaN
671  Cancelled  408-9630926-2785104         SET268-KR-NP-M    0     NaN
672  Cancelled  403-5342526-7867558        MEN5019-KR-XXXL    0     NaN
675  Cancelled  405-6041428-1576346       SET293-KR-NP-XXL    0     NaN
691  Cancelled  406-1694518-5618746           JNE3691-TU-L    0     NaN
708  Cancelled  402-5014156-9264316        JNE3373-KR-XXXL    0     NaN
711  Cancelled  402-5903377-6817119             J0094-KR-M    0     NaN
713  Cancelled  405-9099443-7445111       SET364-KR-NP-XXL    0     NaN

In [24]:
Amazon_sale_df[Amazon_sale_df['Amount'].isna()]['Status'].value_counts(dropna=False)

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [25]:
median_value = Amazon_sale_df['Amount'].median(skipna=True)

In [26]:
mask_returned = Amazon_sale_df['Status'].str.contains('Returned to Seller', na=False)
print("Returned rows with missing Amount before:", Amazon_sale_df[mask_returned & Amazon_sale_df['Amount'].isna()].shape[0])

Amazon_sale_df.loc[mask_returned & Amazon_sale_df['Amount'].isna(), 'Amount'] = 0

print("Returned rows with missing Amount after:", Amazon_sale_df[mask_returned & Amazon_sale_df['Amount'].isna()].shape[0])

Returned rows with missing Amount before: 3
Returned rows with missing Amount after: 0

In [27]:
mask_pending = Amazon_sale_df['Status'].str.strip().str.lower() == 'pending'
print("Pending rows with missing Amount before:", Amazon_sale_df[mask_pending & Amazon_sale_df['Amount'].isna()].shape[0])

Amazon_sale_df.loc[mask_pending & Amazon_sale_df['Amount'].isna(), 'Amount'] = 0

print("Pending rows with missing Amount after:", Amazon_sale_df[mask_pending & Amazon_sale_df['Amount'].isna()].shape[0])

Pending rows with missing Amount before: 2
Pending rows with missing Amount after: 0

In [28]:
mask_shipped_delivered = Amazon_sale_df['Status'].str.contains('Delivered to Buyer|Shipped', na=False, case=False) \
                        & ~Amazon_sale_df['Status'].str.contains('Returned to Seller', na=False, case=False)

print("Shipped/Delivered rows with missing Amount before:", Amazon_sale_df[mask_shipped_delivered & Amazon_sale_df['Amount'].isna()].shape[0])

Amazon_sale_df.loc[mask_shipped_delivered & Amazon_sale_df['Amount'].isna(), 'Amount'] = median_value

print("Shipped/Delivered rows with missing Amount after:", Amazon_sale_df[mask_shipped_delivered & Amazon_sale_df['Amount'].isna()].shape[0])

Shipped/Delivered rows with missing Amount before: 216
Shipped/Delivered rows with missing Amount after: 0

In [29]:
Amazon_sale_df[Amazon_sale_df['Amount'].isna()][['Status','Order ID','SKU','Qty','Amount']]

           Status             Order ID                  SKU  Qty  Amount
8       Cancelled  407-5443024-5233168  SET200-KR-NP-A-XXXL    0     NaN
29      Cancelled  404-5933402-8801952  JNE2132-KR-398-XXXL    0     NaN
65      Cancelled  171-4137548-0481151       JNE3373-KR-XXL    0     NaN
84      Cancelled  403-9950518-0349133         JNE3510-KR-M    0     NaN
95      Cancelled  405-9112089-3379536         JNE3405-KR-L    0     NaN
...           ...                  ...                  ...  ...     ...
128903  Cancelled  406-3923120-4345139         JNE3801-KR-M    0     NaN
128907  Cancelled  403-6757403-6097100     NW014-ST-SR-XXXL    0     NaN
128908  Cancelled  403-6757403-6097100     NW007-ST-CP-XXXL    0     NaN
128958  Cancelled  408-9513596-4393945       SET058-KR-NP-L    0     NaN
128967  Cancelled  404-5182288-1653947        JNE3638-KR-XS    0     NaN

[7574 rows x 5 columns]

In [30]:
Amazon_sale_df.loc[
    Amazon_sale_df['Status'].str.strip().str.lower() == 'shipping',
    'Amount'] = Amazon_sale_df.loc[
  Amazon_sale_df['Status'].str.strip().str.lower() == 'shipping',
    'Amount'].fillna(median_value)

In [31]:
Amazon_sale_df.dropna(
    subset=['ship-city', 'ship-state', 'ship-postal-code', 'ship-country'],
    inplace=True)

In [32]:
Amazon_sale_df['Status'].value_counts()

Status
Shipped                          77788
Shipped - Delivered to Buyer     28762
Cancelled                        18325
Shipped - Returned to Seller      1950
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [33]:
Amazon_sale_df.describe()

               index            Qty         Amount  ship-postal-code
count  128942.000000  128942.000000  121378.000000     128942.000000
mean    64487.184920       0.904445     648.466174     463966.236509
std     37230.924392       0.313340     280.993751     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32246.250000       1.000000     449.000000     382421.000000
50%     64485.500000       1.000000     605.000000     500033.000000
75%     96730.750000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [34]:
Amazon_sale_df['Date'] = pd.to_datetime(Amazon_sale_df['Date'], errors='coerce')

/tmp/ipython-input-4265130726.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Amazon_sale_df['Date'] = pd.to_datetime(Amazon_sale_df['Date'], errors='coerce')

In [35]:
Amazon_sale_df['Date'].isna().sum()

np.int64(0)

In [36]:
Amazon_sale_df['Year'] = Amazon_sale_df['Date'].dt.year
Amazon_sale_df['Month'] = Amazon_sale_df['Date'].dt.month
Amazon_sale_df['Month_Name'] = Amazon_sale_df['Date'].dt.strftime('%B')
Amazon_sale_df['Day'] = Amazon_sale_df['Date'].dt.day
Amazon_sale_df['Weekday'] = Amazon_sale_df['Date'].dt.strftime('%A')

In [37]:
Amazon_sale_df[['Date', 'Year', 'Month', 'Month_Name', 'Weekday']].head()

        Date  Year  Month Month_Name   Weekday
0 2022-04-30  2022      4      April  Saturday
1 2022-04-30  2022      4      April  Saturday
2 2022-04-30  2022      4      April  Saturday
3 2022-04-30  2022      4      April  Saturday
4 2022-04-30  2022      4      April  Saturday

In [38]:
Amazon_sale_df.to_csv('/content/Amazon_Sales_Cleaned.csv', index=False)

In [39]:
from google.colab import files
files.download('/content/Amazon_Sales_Cleaned.csv')